// Building 9 Room Data
export const building9Rooms = {
  'Ground Floor': [
    { id: '9-101', name: '9-101', description: 'Deans Office' },
    { id: 'CR-GF', name: 'CR', description: 'Comfort Room' },
    { id: '9-103', name: '9-103', description: 'Lorem Ipsum' },
    { id: '9-104', name: '9-104', description: 'Lorem Ipsum' },
    { id: '9-105', name: '9-105', description: 'Lorem Ipsum' },
    { id: '9-106', name: '9-106', description: 'Lorem Ipsum' },
    { id: '9-107', name: '9-107', description: 'Lorem Ipsum' },
  ],
  '2nd Floor': [
    { id: 'DTO', name: 'DTO', description: 'DTO office' },
    { id: 'CR-2F', name: 'CR', description: 'Comfort Room' },
    { id: '9-202', name: '9-202', description: 'Lorem Ipsum' },
    { id: '9-203', name: '9-203', description: 'Lorem Ipsum' },
    { id: '9-204', name: '9-204', description: 'Lorem Ipsum' },
    { id: '9-205', name: '9-205', description: 'Lorem Ipsum' },
    { id: '9-206', name: '9-206', description: 'Lorem Ipsum' },
    { id: '9-207', name: '9-207', description: 'Lorem Ipsum' },
  ],
  '3rd Floor': [
    { id: 'Office-3F', name: 'Office', description: 'Office' },
    { id: 'CR-3F', name: 'CR', description: 'Comfort Room' },
    { id: '9-302', name: '9-302', description: 'Computer Laboratory' },
    { id: '9-303', name: '9-303', description: 'Computer Laboratory' },
    { id: '9-304', name: '9-304', description: 'Computer Laboratory' },
    { id: '9-305', name: '9-305', description: 'Computer Laboratory' },
    { id: '9-306', name: '9-306', description: 'Computer Laboratory' },
    { id: '9-307', name: '9-307', description: 'Computer Laboratory' },
    { id: '9-308', name: '9-308', description: 'Computer Laboratory' },
    { id: '9-309', name: '9-309', description: 'Computer Laboratory' },
  ],
  '4th Floor': [
    { id: 'Faculty-4F', name: 'Faculty Office', description: 'Faculty Office' },
    { id: 'CR-4F', name: 'CR', description: 'Comfort Room' },
    { id: '9-402', name: '9-402', description: 'Lorem Ipsum' },
    { id: '9-403', name: '9-403', description: 'Lorem Ipsum' },
    { id: '9-404', name: '9-404', description: 'Lorem Ipsum' },
    { id: '9-405', name: '9-405', description: 'Lorem Ipsum' },
    { id: '9-406', name: '9-406', description: 'Lorem Ipsum' },
    { id: '9-407', name: '9-407', description: 'Lorem Ipsum' },
  ],
};
