const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#34495e' },
  header: {
    position: 'absolute', top: 30, left: 20, right: 20, flexDirection: 'row', justifyContent: 'space-between', zIndex: 1
  },
  headerButtonLeft: {
    backgroundColor: '#28a745', padding: 8, borderRadius: 8, alignItems: 'center', justifyContent: 'center', width: 60, height: 40,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  headerButtonCenter: {
    backgroundColor: '#28a745', padding: 8, borderRadius: 8, alignItems: 'center', flexDirection: 'row', justifyContent: 'center', width: 150, height: 40,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  headerButtonRight: {
    backgroundColor: '#28a745', padding: 8, borderRadius: 8, alignItems: 'center', justifyContent: 'center', width: 60, height: 40,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  
  // NEW STYLE: Pathfinding Button positioned below Search
  pathfindingButtonBelowSearch: {
    position: 'absolute',
    top: 130, // moved lower to make room for filter button
    right: 20, // Aligned with header button
    backgroundColor: '#28a745', // Same green
    padding: 8,
    borderRadius: 8, // Same radius
    alignItems: 'center',
    justifyContent: 'center',
    width: 60, // Same width
    height: 40, // Same height
    zIndex: 10,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },

  // Filter Button placed between Search and Pathfinding (right side)
  filterButtonBetween: {
    position: 'absolute',
    top: 80, // between header (30) and pathfinding (130)
    right: 20,
    backgroundColor: '#28a745',
    padding: 8,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    width: 60,
    height: 40,
    zIndex: 10,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },

  buttonText: { color: 'white', textAlign: 'center', marginLeft: 8 },
  imageContainer: { flex: 1 },
  mapImage: { width: '100%', height: '100%' },
  modalContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: 'rgba(0,0,0,0.5)' },
  modalContent: { backgroundColor: '#f5f5f5', padding: 0, borderRadius: 10, width: '80%', overflow: 'hidden' },
  modalTitle: { fontSize: 18, fontWeight: 'bold', marginBottom: 10 },
  modalTitleWhite: { fontSize: 18, fontWeight: 'bold', color: '#333' },
  modalDescription: { marginBottom: 10, fontWeight: 'bold' },
  modalText: { fontSize: 14, marginBottom: 5 },
  line: { borderBottomWidth: 1, borderBottomColor: '#ccc', marginVertical: 10 },
  lineDark: { borderBottomWidth: 1, borderBottomColor: '#e0e0e0', marginVertical: 0 },
  modalHeaderWhite: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 15,
    backgroundColor: 'white',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
  },
  pinImage: { width: '100%', height: 200, borderRadius: 10, marginVertical: 10 },
  actionButtons: { flexDirection: 'row', justifyContent: 'space-between' },
  iconButton: { backgroundColor: '#28a745', padding: 10, borderRadius: 5, flexDirection: 'row', alignItems: 'center', elevation: 5, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.25, shadowRadius: 3.84 },
  closeButton: { backgroundColor: '#05bbf7', padding: 10, borderRadius: 5, marginTop: 10, elevation: 5, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.25, shadowRadius: 3.84 },
  footer: { position: 'absolute', bottom: 30, left: 20, right: 20, flexDirection: 'row', justifyContent: 'space-between', zIndex: 1 },
  footerButton: { backgroundColor: '#28a745', padding: 8, borderRadius: 8, alignItems: 'center', justifyContent: 'center', width: 60, height: 40, elevation: 5, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.25, shadowRadius: 3.84 },
  
  bottomNavCard: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#f5f5f5',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 0,
    paddingBottom: 0,
    zIndex: 10,
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    overflow: 'hidden',
  },
  locationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
  },
  locationItem: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e0e0e0',
    borderRadius: 10,
    padding: 8,
    backgroundColor: 'white'
  },
  locationIconContainer: {
    width: 35,
    height: 35,
    borderRadius: 17.5,
    backgroundColor: '#e8f5e9',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  locationTextContainer: {
    flex: 1,
  },
  locationLabel: {
    fontSize: 10,
    color: '#999',
    marginBottom: 2,
    textTransform: 'uppercase'
  },
  locationValue: {
    fontSize: 14,
    color: '#333',
    fontWeight: '500',
  },
  swapButtonSmall: {
    padding: 8,
    marginLeft: 10,
  },
  goNowButton: {
    backgroundColor: '#4caf50',
    borderRadius: 12,
    paddingVertical: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  goNowButtonDisabled: {
    backgroundColor: '#ccc',
  },
  goNowButtonText: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
  },
  middleFooterButton: {
    backgroundColor: '#28a745', 
    padding: 8, 
    borderRadius: 8, 
    alignItems: 'center', 
    flexDirection: 'row', 
    justifyContent: 'center', 
    width: 150, 
    height: 40,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  pinsModalPanel: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#f5f5f5',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: '85%',
    zIndex: 10,
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  pinsModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 15,
    backgroundColor: 'white',
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  pinsModalCampusTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#ff8c00',
    flex: 1,
  },
  switchButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#4a4a4a',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 5,
    marginRight: 10,
  },
  switchButtonText: {
    color: 'white',
    fontSize: 12,
    fontWeight: '600',
    marginLeft: 5,
  },
  facilitiesTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#000',
    paddingHorizontal: 20,
    paddingTop: 15,
    paddingBottom: 8,
    backgroundColor: '#f5f5f5',
  },
  facilityList: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  facilityListContent: {
    paddingHorizontal: 20,
    paddingBottom: 20,
  },
  facilityButton: {
    backgroundColor: '#4a4a4a',
    borderRadius: 10,
    marginBottom: 8,
    overflow: 'hidden',
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 60,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  facilityButtonImage: {
    width: '100%',
    height: '100%',
    opacity: 0.3,
    position: 'absolute',
  },
  facilityButtonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 10,
    zIndex: 1,
    flex: 1,
  },
  facilityNumber: {
    fontSize: 22,
    fontWeight: 'bold',
    color: 'white',
    marginRight: 12,
    minWidth: 30,
  },
  facilityName: {
    fontSize: 14,
    fontWeight: '600',
    color: 'white',
    flex: 1,
  },
  pinItem: { borderBottomWidth: 1, borderBottomColor: '#ccc', paddingVertical: 10, paddingHorizontal: 5, width: '100%' },
  pinDescription: { fontSize: 14, color: '#666' },
  pinsModalContent: { backgroundColor: '#f5f5f5', padding: 0, borderRadius: 10, width: '80%', maxHeight: '80%', overflow: 'hidden' },
  locationPickerList: { maxHeight: 400, marginVertical: 10 },
  locationPickerItem: { 
    borderBottomWidth: 1, 
    borderBottomColor: '#e0e0e0', 
    paddingVertical: 15, 
    paddingHorizontal: 15, 
    width: '100%',
    backgroundColor: '#f5f5f5',
    borderRadius: 5,
    marginBottom: 5,
  },
  locationPickerDescription: { 
    fontSize: 16, 
    color: '#333',
    fontWeight: '500',
  },
  searchContainer: { 
    position: 'absolute', 
    top: 80, 
    left: 90, 
    right: 90, 
    backgroundColor: '#f5f5f5', 
    borderRadius: 10, 
    overflow: 'hidden',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  campusContainer: { 
    position: 'absolute', 
    top: 80, 
    left: 90, 
    right: 90, 
    backgroundColor: '#f5f5f5', 
    borderRadius: 10, 
    zIndex: 5,
    overflow: 'hidden',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  searchInput: { 
    borderWidth: 1, 
    borderColor: '#ccc', 
    padding: 10, 
    borderRadius: 5, 
    marginBottom: 10,
    backgroundColor: 'white',
    color: '#333',
  },
  searchItemContainer: {
    padding: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
    backgroundColor: '#f5f5f5',
  },
  searchItem: { 
    padding: 0,
  },
  searchTitle: { fontWeight: 'bold' },
  searchDescription: { fontStyle: 'italic', color: '#333' },
  closeText: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center'
  },
  
  // Alert Modal Styles
  alertModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  alertModalContainer: {
    backgroundColor: '#f5f5f5',
    borderRadius: 10,
    padding: 0,
    width: '80%',
    maxWidth: 400,
    overflow: 'hidden',
  },
  alertModalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 15,
    color: '#000',
  },
  alertModalMessage: {
    fontSize: 16,
    color: '#333',
    marginBottom: 20,
    lineHeight: 22,
  },
  alertModalButton: {
    backgroundColor: '#007AFF',
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 24,
    alignSelf: 'flex-end',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  alertModalButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '600',
  },
  filterModalContent: { backgroundColor: '#f5f5f5', padding: 0, borderRadius: 10, width: '90%', maxHeight: '80%', overflow: 'hidden' },
  filterTopControls: { 
    flexDirection: 'row', 
    justifyContent: 'flex-end', 
    alignItems: 'center',
    marginBottom: 16, 
    paddingHorizontal: 16, 
    paddingTop: 16,
    gap: 12,
  },
  filterSelectAllButton: {
    backgroundColor: '#28a745',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 6,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
  },
  filterSelectAllButtonText: {
    color: 'white',
    fontSize: 14,
    fontWeight: '600',
  },
  filterClearAllButton: {
    backgroundColor: '#dc3545',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 6,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
  },
  filterClearAllButtonText: {
    color: 'white',
    fontSize: 14,
    fontWeight: '600',
  },
  categoryGroup: { 
    marginBottom: 20,
    paddingBottom: 12,
  },
  categoryHeaderContainer: {
    marginBottom: 12,
  },
  categoryHeaderText: { 
    fontWeight: 'bold', 
    fontSize: 16,
    marginBottom: 4,
    color: '#000' 
  },
  categoryHeaderUnderline: {
    height: 1,
    backgroundColor: '#000',
    width: '100%',
  },
  filterCategoryButton: {
    borderRadius: 8,
    marginBottom: 8,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    overflow: 'hidden',
    height: 60,
  },
  filterCategoryButtonImage: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
  },
  filterCategoryButtonImageStyle: {
    borderRadius: 8,
  },
  filterCategoryButtonSelected: {
    borderWidth: 4,
    borderColor: '#4CAF50',
  },
  filterCategoryButtonContent: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 12,
    backgroundColor: 'rgba(74, 74, 74, 0.7)',
  },
  filterCategoryButtonText: {
    color: 'white',
    fontSize: 14,
    fontWeight: '500',
    flex: 1,
  },
  categoryItem: { flexDirection: 'row', alignItems: 'center', paddingVertical: 6 },
  checkboxLabel: { marginLeft: 10, color: '#333' },
  settingsModalBackdrop: { backgroundColor: 'rgba(0,0,0,0.5)' },
  settingsScreen: { flex: 1, backgroundColor: '#f5f5f5', paddingTop: 0, padding: 0, paddingBottom: 0 },
  settingsTabRow: {
    flexDirection: 'row',
    marginBottom: 0,
    paddingTop: 10,
  },
  settingsTabButton: {
    flex: 1,
    paddingVertical: 12,
    alignItems: 'center',
    borderRadius: 8,
    marginHorizontal: 4,
  },
  settingsTabActive: {
    backgroundColor: '#28a745',
  },
  aboutContent: { flex: 1, marginVertical: 20, paddingBottom: 100 },
  settingsPlaceholder: { fontSize: 14, color: '#999', fontStyle: 'italic' },
  aboutSection: { paddingVertical: 10 },
  aboutTitle: { fontSize: 22, fontWeight: 'bold', color: '#333', marginBottom: 8 },
  aboutLine: { borderBottomWidth: 2, borderBottomColor: '#28a745', marginVertical: 12 },
  aboutLabel: { fontSize: 14, fontWeight: '600', color: '#555', marginBottom: 12 },
  membersList: { paddingLeft: 8, marginBottom: 16 },
  memberItem: { fontSize: 14, color: '#666', paddingVertical: 6, paddingLeft: 8, borderLeftWidth: 3, borderLeftColor: '#28a745' },
  classYear: { fontSize: 14, fontWeight: 'bold', color: '#28a745', marginTop: 12 },
  settingsTabText: { color: '#333' },
  settingsTabActiveText: { color: '#fff' },
});
